version: '3.7'

networks:
  localnet:

volumes:
  db_data:

services:
  web:
    image: sherifsadek/tracker_frontend:latest
    container_name: front
    ports:
    - "8000:3000"
    networks:
    - localnet

  backend:
    image: tracker_backend:latest
    container_name: back
    ports:
    - "8500:8081"
    networks:
    - localnet

  db:
    image: postgres:14-alpine
    container_name: pg14
    ports:
    - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql
    environment:
      POSTGRES_PASSWORD: pdwrkstn
      POSTGRES_USER: panorama
      POSTGRES_DB: tracker
    networks:
    - localnet