apiVersion: apps/v1
kind: Deployment                                          
metadata:
  name: tracker-frontend-pod
  labels:
    app: tracker
spec:
  selector:
    matchLabels:
      app: tracker
  strategy:
    type: RollingUpdate                                   
    rollingUpdate: 
      maxUnavailable: 1                                   
      maxSurge: 1                                         
  template:
    metadata:
      labels:
        app: tracker                                 
    spec:
      containers:
        - image: sherifsadek/tracker_frontend:latest
          imagePullPolicy: IfNotPresent                         
          name: tracker
          ports:
            - containerPort: 3000
