apiVersion: apps/v1
kind: Deployment                                          
metadata:
  name: tracker-backend
  labels:
    app: tracker-backend
spec:
  selector:
    matchLabels:
      app: tracker-backend
  strategy:
    type: RollingUpdate                                   
    rollingUpdate: 
      maxUnavailable: 1                                   
      maxSurge: 1                                         
  template:
    metadata:
      labels:
        app: tracker-backend                                 
    spec:
      containers:
        - image: sherifsadek/tracker_backend:latest
          imagePullPolicy: IfNotPresent
          name: tracker-backend
          ports:
            - containerPort: 8080
          env:
            - name: PGHOST
              value: postgres
            - name: PGDATABASE
              value: tracker
            - name: PGUSER
              value: panorama
            - name: PGPASSWORD
              value: pdwrkstn  
